CREATE OR REPLACE VIEW PRODUCT_ROL_QUERY_VIEW AS
SELECT 	PRODUCT_VIEW.PDT_ID,
		PRODUCT_VIEW.PDT_NAME,
        (CASE
        WHEN ROL_PRODUCT.ROL_ID = 1 THEN
            TRUE
        ELSE
            FALSE
        END) as 'IS_RELATIONED',
        NOW() as 'TIME_COLUMN'
        FROM PRODUCT_VIEW
        LEFT JOIN ROL_PRODUCT ON PRODUCT_VIEW.PDT_ID = ROL_PRODUCT.PDT_ID
        LEFT JOIN ROL_VIEW ON ROL_VIEW.ROL_ID = ROL_PRODUCT.ROL_ID
        group by PRODUCT_VIEW.PDT_NAME;
        
        
        
        
DROP PROCEDURE GET_PRODUCT_ROL_QUERY_VIEW;
DELIMITER $$
CREATE PROCEDURE  GET_PRODUCT_ROL_QUERY_VIEW
(
	IN 	rolID	INT
)
BEGIN

	SELECT 	PRODUCT_VIEW.PDT_ID,
		PRODUCT_VIEW.PDT_NAME,
        (CASE
        WHEN ROL_PRODUCT.ROL_ID = rolID THEN
            TRUE
        ELSE
            FALSE
        END) as 'IS_RELATIONED',
                NOW() as 'TIME_COLUMN'
         FROM PRODUCT_VIEW
        LEFT JOIN ROL_PRODUCT ON PRODUCT_VIEW.PDT_ID = ROL_PRODUCT.PDT_ID
        LEFT JOIN ROL_VIEW ON ROL_VIEW.ROL_ID = ROL_PRODUCT.ROL_ID
        group by PRODUCT_VIEW.PDT_NAME;

END $$

CALL GET_PRODUCT_ROL_QUERY_VIEW(1);